ontology_pkg: mc_mdl_tomasys
ontology_path: tomasys.owl
# where is ros_navigation.owl ??
domain_ontology_pkg: mros1_reasoner
domain_ontology_path: owl/ros_navigation.owl

function: f_navigate

configs: ['f1_v1_r1','f1_v1_r2','f1_v1_r3','f1_v2_r1','f1_v2_r2','f1_v2_r3','f1_v3_r1','f1_v3_r2','f1_v3_r3','f2_v1_r1','f2_v1_r2','f2_v1_r3','f2_v2_r1','f2_v2_r2','f2_v2_r3','f2_v3_r1','f2_v3_r2','f2_v3_r3','f3_v1_r1','f3_v1_r2','f3_v1_r3','f3_v2_r1','f3_v2_r2','f3_v2_r3','f3_v3_r1','f3_v3_r2','f3_v3_r3']

result_file: kb.owl
